### ISSUE TITLE
要是加个中文的README就好了

### ISSUE THREAD

**Issue by Murong-WangKezi** [MFn233/Auto-Clicker#2]

**Comment by MFn233** [comment]
暂时先别用，有巨大bug

**Comment by MFn233** [comment]
严重占用CPU

**Comment by MFn233** [comment]
因为一个循环system("cls")

**Comment by MFn233** [comment]
对不起打扰你的邮箱，但是
我打算重构

**Comment by Murong-WangKezi** [comment]
没有打扰啦，对啦我是从PCL2的链接来这个项目的

**Comment by MFn233** [comment]
啊哈

**Comment by Murong-WangKezi** [comment]
我测了一下CPU占用正常呀，1.2%不是很高

**Comment by Murong-WangKezi** [comment]
还有就是希望加入快捷键启动和停止连点，不然有的时候关不掉

**Comment by MFn233** [comment]
不知道是不是这个版本改了
反正之前搞废过一台电脑
8000￥

**Comment by MFn233** [comment]
不知道是不是真废了，反正让我失去了一个朋友（

**Comment by Murong-WangKezi** [comment]
你回复挺快，谢谢呀

**Comment by MFn233** [comment]
正好在看~

**Comment by MFn233** [comment]
我知道了，这个仓库里的版本修改了
![image](https://github.com/user-attachments/assets/ba8ea25b-940c-459a-8754-f731a9db1e77)

**Comment by MFn233** [comment]
不用system了

但缺点是没法用conhost。
不过我觉得大家用的应该都是terminal吧？

**Comment by Murong-WangKezi** [comment]
cls很吃CPU吗

**Comment by MFn233** [comment]
本身不吃CPU，但循环cls就吃了（

**Comment by MFn233** [comment]
之前恐怖的能达到90%的cpu都是一个叫system的进程

**Comment by Murong-WangKezi** [comment]
我不太懂C++qwq

**Comment by MFn233** [comment]
az

**Comment by MFn233** [comment]
反正我加了中文readme了（
